"""
Builds the dark theme for every stylesheet in css/.

For each color rule in a stylesheet it writes a matching rule under
:root[data-theme="dark"] at the end of the same file, between the
DARK THEME markers. Light rules are never changed.

    python tools/dark-theme.py

Run it again after changing colors in css/*.css; it replaces the old
dark block. Hand-tuned dark fixes live in css/theme.css (not generated).

How it keeps the cascade intact: every declaration of a color property
is mirrored (even "transparent", "none", "inherit"), and every mirrored
rule gets the same extra specificity, so dark rules win over each other
exactly the way the light rules do.
"""

import colorsys
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSS_DIR = ROOT / "css"
SKIP = {"theme.css", "admin.css"}  # hand-written, already theme-aware

START = "/* ===== DARK THEME (generated by tools/dark-theme.py — do not edit by hand) ===== */"
END = "/* ===== END DARK THEME ===== */"
PREFIX = ':root[data-theme="dark"]'

NEUTRAL_HUE = 220 / 360


# ---------------------------------------------------------------- colors

COLOR_RE = re.compile(r"#[0-9a-fA-F]{3,8}\b|rgba?\([^)]*\)|\bwhite\b|\bblack\b", re.I)


def parse_color(tok):
    t = tok.strip().lower()
    if t == "white":
        return (1.0, 1.0, 1.0, 1.0)
    if t == "black":
        return (0.0, 0.0, 0.0, 1.0)
    if t.startswith("#"):
        h = t[1:]
        if len(h) in (3, 4):
            h = "".join(c * 2 for c in h)
        if len(h) not in (6, 8):
            return None
        r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
        a = int(h[6:8], 16) / 255 if len(h) == 8 else 1.0
        return (r, g, b, a)
    m = re.match(r"rgba?\((.*)\)$", t)
    if m:
        parts = [p for p in re.split(r"[\s,/]+", m.group(1).strip()) if p]
        if len(parts) < 3:
            return None

        def num(p, scale):
            return float(p[:-1]) / 100 if p.endswith("%") else float(p) / scale

        r, g, b = (num(p, 255) for p in parts[:3])
        a = num(parts[3], 1) if len(parts) > 3 else 1.0
        return (r, g, b, a)
    return None


def fmt(r, g, b, a=1.0):
    r, g, b = (max(0, min(255, round(v * 255))) for v in (r, g, b))
    if a >= 0.999:
        return "#%02x%02x%02x" % (r, g, b)
    return "rgba(%d, %d, %d, %s)" % (r, g, b, ("%.3f" % a).rstrip("0").rstrip("."))


def hsl(c):
    h, l, s = colorsys.rgb_to_hls(*c[:3])
    return h, s, l


def from_hsl(h, s, l, a):
    r, g, b = colorsys.hls_to_rgb(h, max(0, min(1, l)), max(0, min(1, s)))
    return fmt(r, g, b, a)


def vivid(s, l):
    return s >= 0.5 and 0.2 < l < 0.75


def tinted(h, s, l):
    """A pale color with a real hue (blue/green/amber tint), not the site's cool grays."""
    if s < 0.4 or l >= 0.985:
        return False
    return not (190 / 360 <= h <= 235 / 360 and s < 0.6)


def map_bg(c, page=False):
    h, s, l = hsl(c)
    a = c[3]
    if vivid(s, l):
        # Brand fills (blue buttons, green/red badges) stay; faint tints get a bit stronger.
        return fmt(*c[:3], min(0.35, a * 2) if a < 0.3 else a)
    if l >= 0.5:
        if page:
            return from_hsl(NEUTRAL_HUE, 0.28, 0.075, a)
        if l >= 0.97:
            L = 0.115 + (1 - l) * 1.6
        elif l >= 0.85:
            L = 0.163 + (0.97 - l) * 0.8
        else:
            L = 0.259 + (0.85 - l) * 0.3
        tint = tinted(h, s, l)
        return from_hsl(h if tint else NEUTRAL_HUE, min(s, 0.38) if tint else 0.22, L, a)
    if a < 1:
        return fmt(*c)  # scrims and overlays stay dark
    return from_hsl(h if s >= 0.4 else NEUTRAL_HUE, min(s, 0.3), 0.22 + l * 0.3, a)


def map_fg(c):
    h, s, l = hsl(c)
    a = c[3]
    if s >= 0.4 and l < 0.9:
        if l < 0.3 and 195 / 360 <= h <= 255 / 360:
            return from_hsl(h, min(s, 0.25), 0.88 - l * 0.3, a)  # navy ink → light text
        if l < 0.62:
            return from_hsl(h, min(s, 0.85), 0.66 + (0.62 - l) * 0.1, a)
        return fmt(*c)
    if l >= 0.9:
        return fmt(*c)  # white text sits on colored fills
    return from_hsl(h if s > 0.05 else NEUTRAL_HUE, min(s, 0.2), 0.94 - 0.62 * l, a)


def map_border(c):
    h, s, l = hsl(c)
    a = c[3]
    if s >= 0.4 and l < 0.75:
        return fmt(*c) if l >= 0.42 else from_hsl(h, min(s, 0.7), 0.42, a)
    if l >= 0.6:
        if tinted(h, s, l):
            return from_hsl(h, min(s, 0.45), 0.22 + (1 - l) * 0.4, a)
        return from_hsl(NEUTRAL_HUE, 0.2, min(0.36, 0.12 + (1 - l)), a)
    return map_fg(c)


def map_shadow_color(c, ring):
    h, s, l = hsl(c)
    a = c[3]
    if ring:
        if s < 0.4 and l >= 0.6:
            return map_bg(c)
        if vivid(s, l) and a < 0.3:
            return fmt(*c[:3], min(0.4, a * 2))
        return map_border(c)
    if vivid(s, l):
        return fmt(*c)  # colored glows under buttons
    if l < 0.5:
        return fmt(*c[:3], min(0.6, a * 1.8 + 0.04))  # shadows need more weight on dark
    return map_bg(c)


# ---------------------------------------------------------------- values

def split_top(value, sep):
    """Split on sep outside parentheses and quotes."""
    out, depth, quote, cur = [], 0, None, ""
    for ch in value:
        if quote:
            cur += ch
            if ch == quote:
                quote = None
            continue
        if ch in "\"'":
            quote = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == sep and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    out.append(cur)
    return out


def protect_urls(value):
    """Replace url(...) with placeholders so colors inside data URIs are left alone."""
    urls = []

    def keep(m):
        urls.append(m.group(0))
        return "\x00%d\x00" % (len(urls) - 1)

    return re.sub(r"url\((?:[^()\"']|\"[^\"]*\"|'[^']*')*\)", keep, value), urls


def restore_urls(value, urls):
    return re.sub(r"\x00(\d+)\x00", lambda m: urls[int(m.group(1))], value)


COLOR_VARS = set()


def rewrite_vars(value, suffix):
    if not suffix:
        return value
    return re.sub(r"var\(\s*(--[\w-]+)",
                  lambda m: "var(%s%s" % (m.group(1), suffix) if m.group(1) in COLOR_VARS else m.group(0),
                  value)


def map_value(value, mapper, var_suffix=""):
    value, urls = protect_urls(value)

    def sub(m):
        c = parse_color(m.group(0))
        return mapper(c) if c else m.group(0)

    value = COLOR_RE.sub(sub, value)
    value = rewrite_vars(value, var_suffix)
    return restore_urls(value, urls)


def has_color(value):
    v, _ = protect_urls(value)
    return bool(COLOR_RE.search(v))


def map_shadow(value):
    if value.strip().lower() in ("none", "inherit", "initial", "unset"):
        return value
    layers = []
    for layer in split_top(value, ","):
        v, urls = protect_urls(layer)
        lengths = re.findall(r"(?<![\w#.-])-?\d*\.?\d+(?:px|rem|em)?(?![\w%])", COLOR_RE.sub(" ", v))
        nums = [float(re.sub(r"[a-z]+$", "", x) or 0) for x in lengths]
        ring = len(nums) >= 3 and nums[0] == 0 and nums[1] == 0 and nums[2] == 0
        v = COLOR_RE.sub(lambda m: map_shadow_color(parse_color(m.group(0)), ring) if parse_color(m.group(0)) else m.group(0), v)
        v = rewrite_vars(v, "--bd")
        layers.append(restore_urls(v, urls))
    return ",".join(layers)


IMAGE_FN = re.compile(r"^(?:repeating-)?(?:linear|radial|conic)-gradient\(|^url\(|^image-set\(", re.I)


def background_parts(value, page=False):
    """Split a background shorthand into (color, image) for its dark mirror."""
    v = value.strip()
    if v.lower() in ("inherit", "initial", "unset", "revert"):
        return v, v
    images, color = [], None
    for layer in split_top(v, ","):
        for tok in split_top(layer.strip(), " "):
            t = tok.strip()
            if not t:
                continue
            if IMAGE_FN.match(t):
                images.append(t)
            elif parse_color(t) or t.lower() in ("transparent", "currentcolor") or t.startswith("var("):
                color = t
    image = ", ".join(map_value(i, map_bg) for i in images) if images else "none"
    color = map_value(color, lambda c: map_bg(c, page)) if color else "transparent"
    return color, image


FG_PROPS = {"color", "fill", "stroke", "caret-color", "text-decoration-color",
            "-webkit-text-fill-color", "column-rule-color", "accent-color", "scrollbar-color"}
BG_PROPS = {"background-color"}
BORDER_PROPS = {"border-color", "border-top-color", "border-right-color", "border-bottom-color",
                "border-left-color", "border-block-color", "border-inline-color",
                "border-block-start-color", "border-block-end-color",
                "border-inline-start-color", "border-inline-end-color", "outline-color"}
BORDER_SHORTHANDS = {"border": "border-color", "border-top": "border-top-color",
                     "border-right": "border-right-color", "border-bottom": "border-bottom-color",
                     "border-left": "border-left-color", "border-block": "border-block-color",
                     "border-inline": "border-inline-color", "outline": "outline-color"}
SHADOW_PROPS = {"box-shadow", "text-shadow"}


def border_color_of(value):
    v = value.strip()
    if v.lower() in ("inherit", "initial", "unset", "revert"):
        return v
    for tok in split_top(v, " "):
        t = tok.strip()
        if parse_color(t) or t.lower() in ("transparent", "currentcolor") or t.startswith("var("):
            return map_value(t, map_border, "--bd")
    return "currentColor"


def mirror(prop, value, page_bg):
    """Dark declarations (prop, value) for one light declaration."""
    p = prop.lower()
    if p.startswith("--"):
        if has_color(value):
            return [(prop, map_value(value, lambda c: map_bg(c, page_bg))),
                    (prop + "--fg", map_value(value, map_fg)),
                    (prop + "--bd", map_value(value, map_border))]
        refs = re.fullmatch(r"\s*var\(\s*(--[\w-]+)\s*\)\s*", value)
        if refs and refs.group(1) in COLOR_VARS:
            v = refs.group(1)
            return [(prop + "--fg", "var(%s--fg)" % v), (prop + "--bd", "var(%s--bd)" % v)]
        return []
    if p in FG_PROPS:
        return [(prop, map_value(value, map_fg, "--fg"))]
    if p in BG_PROPS:
        return [(prop, map_value(value, lambda c: map_bg(c, page_bg)))]
    if p == "background-image":
        return [(prop, map_value(value, map_bg))]
    if p == "background":
        color, image = background_parts(value, page_bg)
        return [("background-color", color), ("background-image", image)]
    if p in BORDER_PROPS:
        return [(prop, map_value(value, map_border, "--bd"))]
    if p in BORDER_SHORTHANDS:
        return [(BORDER_SHORTHANDS[p], border_color_of(value))]
    if p in SHADOW_PROPS:
        return [(prop, map_shadow(value))]
    return []


# ---------------------------------------------------------------- parsing

def strip_comments(css):
    out, i, quote = [], 0, None
    while i < len(css):
        ch = css[i]
        if quote:
            out.append(ch)
            if ch == "\\":
                out.append(css[i + 1])
                i += 2
                continue
            if ch == quote:
                quote = None
            i += 1
            continue
        if ch in "\"'":
            quote = ch
        if css.startswith("/*", i):
            j = css.find("*/", i + 2)
            i = len(css) if j < 0 else j + 2
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def read_block(css, i):
    """css[i] is just after '{'; return (body, index after matching '}')."""
    depth, quote, j = 1, None, i
    while j < len(css):
        ch = css[j]
        if quote:
            if ch == "\\":
                j += 2
                continue
            if ch == quote:
                quote = None
        elif ch in "\"'":
            quote = ch
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return css[i:j], j + 1
        j += 1
    raise ValueError("unbalanced braces")


def parse(css):
    nodes, i, prelude, quote = [], 0, "", None
    while i < len(css):
        ch = css[i]
        if quote:
            prelude += ch
            if ch == quote:
                quote = None
            i += 1
            continue
        if ch in "\"'":
            quote = ch
            prelude += ch
            i += 1
            continue
        if ch == ";" and prelude.strip().startswith("@"):
            prelude = ""  # @import / @charset
            i += 1
            continue
        if ch == "{":
            body, i = read_block(css, i + 1)
            head = " ".join(prelude.split())
            prelude = ""
            if head.startswith(("@media", "@supports")):
                nodes.append(("at", head, parse(body)))
            elif head.startswith("@"):
                continue  # @keyframes, @font-face: no color mirroring needed
            else:
                nodes.append(("rule", head, body))
            continue
        prelude += ch
        i += 1
    return nodes


def declarations(body):
    out = []
    for part in split_top(body, ";"):
        if ":" not in part:
            continue
        prop, value = part.split(":", 1)
        prop = prop.strip()
        value = " ".join(value.split())
        important = bool(re.search(r"!\s*important\s*$", value, re.I))
        value = re.sub(r"\s*!\s*important\s*$", "", value, flags=re.I)
        if prop:
            out.append((prop, value, important))
    return out


def prefix_selector(sel):
    s = sel.strip()
    if s.startswith(":root"):
        return PREFIX + s[len(":root"):]
    m = re.match(r"html\b", s)
    if m:
        return 'html[data-theme="dark"]' + s[4:]
    return PREFIX + " " + s


def is_page(sel):
    return all(re.fullmatch(r"(html|body)", s.strip()) for s in split_top(sel, ","))


def collect_vars(nodes):
    for kind, head, body in nodes:
        if kind == "at":
            collect_vars(body)
            continue
        for prop, value, _ in declarations(body):
            if prop.startswith("--") and has_color(value):
                COLOR_VARS.add(prop)


def collect_var_aliases(nodes):
    changed = False
    for kind, head, body in nodes:
        if kind == "at":
            changed |= collect_var_aliases(body)
            continue
        for prop, value, _ in declarations(body):
            m = re.fullmatch(r"\s*var\(\s*(--[\w-]+)\s*\)\s*", value)
            if prop.startswith("--") and m and m.group(1) in COLOR_VARS and prop not in COLOR_VARS:
                COLOR_VARS.add(prop)
                changed = True
    return changed


def emit(nodes, indent=""):
    lines = []
    for kind, head, body in nodes:
        if kind == "at":
            inner = emit(body, indent + "  ")
            if inner:
                lines.append("%s%s {" % (indent, head))
                lines.extend(inner)
                lines.append("%s}" % indent)
            continue
        page_bg = is_page(head)
        decls = []
        for prop, value, important in declarations(body):
            for p, v in mirror(prop, value, page_bg):
                decls.append("%s: %s%s" % (p, v, " !important" if important else ""))
        if decls:
            selector = ", ".join(prefix_selector(s) for s in split_top(head, ","))
            lines.append("%s%s { %s; }" % (indent, selector, "; ".join(decls)))
    return lines


def main():
    css_dir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else CSS_DIR
    files = sorted(f for f in css_dir.glob("*.css") if f.name not in SKIP)
    sources, newlines = {}, {}
    for f in files:
        raw = f.read_bytes().decode("utf-8")
        newlines[f] = "\r\n" if "\r\n" in raw else "\n"
        start = raw.find(START)
        sources[f] = raw[:start].rstrip() if start >= 0 else raw.rstrip()  # light rules, byte for byte

    parsed = {f: parse(strip_comments(src.replace("\r\n", "\n"))) for f, src in sources.items()}
    for nodes in parsed.values():
        collect_vars(nodes)
    while any(collect_var_aliases(nodes) for nodes in parsed.values()):
        pass

    for f, nodes in parsed.items():
        newline = newlines[f]
        block = emit(nodes)
        text = sources[f]
        if block:
            text += newline * 3 + newline.join([START] + block + [END])
        text += newline
        f.write_bytes(text.encode("utf-8"))
        print("%-18s %4d dark rules" % (f.name, len(block)))


if __name__ == "__main__":
    sys.exit(main())
